algo= input('Digite algo:')
print('O tipo primitivo de {}'.format(type(algo)))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabeto?', algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('Está em maiúsculas?', algo.isupper())
print('Está em minúsculas?', algo.islower())
print('Está capitalizada?', algo.istitle())